### ISSUE TITLE
callback and option_null arg seems to generate wrong syntax code

### ISSUE THREAD

**Issue by eyyub** [klakplok/goji#3]
Hi,

The following code do not compile and seems to generate an .ml file with a wrong syntax:

``` ocaml
callback [curry_arg "alarm" ((option_null (abbrv "alarm")) @@ arg 0)] void
```

In the ml file generate by goji: 

``` ocaml
  (callback
       if (Goji_internal.js_equals args'0 (Goji_internal.js_null)) then (
           None
        ) else (
           (Some  (extract_alarm args'0))
        ));
```

Can you tell me if my code is not good or if in fact it's an error made by goji ?

If not, we just have to add parentheses to make it valid :

``` ocaml
(callback
     (if (Goji_internal.js_equals args'0 (Goji_internal.js_null)) then (
          None
        ) else (
          (Some  (extract_alarm args'0))
         )));
```

It's done by adding () in goji_pprint.ml format_if function:

``` ocaml
(* before *)
let format_if cond bt bf =
  group
    (group (!^"if " ^^ align cond ^^ !^" then (")
     ^^ nest 2 (break 1 ^^ bt) ^^ break 1 ^^ !^") else ("
     ^^ nest 2 (break 1 ^^ bf) ^^ break 1 ^^ !^")")
(* after *)
let format_if cond bt bf =
  group
    (group (!^"(if " ^^ align cond ^^ !^" then (")
     ^^ nest 2 (break 1 ^^ bt) ^^ break 1 ^^ !^") else ("
     ^^ nest 2 (break 1 ^^ bf) ^^ break 1 ^^ !^"))")
```

I can make a pull request but as I don't know if we have to add some () all around in goji_pprint.ml, I will not by precaution ! :D 

Excuse me if I was wrong btw !

Thanks, Eyyub.

**Comment by eyyub** [comment]
See https://github.com/klakplok/goji/pull/4

**Comment by klakplok** [comment]
You fix does the trick. Thanks.
